### ISSUE TITLE
stage_write example using FLEXPATH crashes

### ISSUE THREAD

**Issue by sujin-philip** [ornladios/ADIOS#110]
I am using ADIOS version 1.11.0 on Linux. I want to experiment with staging reads and writes using FLEXPATH. I am trying to run the example in examples/staging/stage_write. I am running these on my local machine with the following commands:

```
/usr/bin/mpirun -np 1 ./genarray_stream staged.out 1 1 1 256 256 256 3 2
```
and
```
/usr/bin/mpirun -np 1 ./stage_write staged.out regular.out FLEXPATH "" MPI ""
```

It looks like the execution is proceeding till connection establishment and then genarray_stream crashes:
```
 Output file(s): staged.out.<step>.bp
 Process number        : 1 x 1 x 1
 Array size per process: 256 x 256 x 256
Writing:  filename               size(GB)    io_time(sec)      GB/s
Unhandled case in cod_print

genarray_stream: /home/sujin/Projects/Adios/Flexpath/build_area/ffs/source/cod/cg.c:354: cg_preprocess: Assertion `FALSE' failed.

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7FDAFEB74E08
#1  0x7FDAFEB73F90
#2  0x7FDAFDBDC4AF
#3  0x7FDAFDBDC428
#4  0x7FDAFDBDE029
#5  0x7FDAFDBD4BD6
#6  0x7FDAFDBD4C81
#7  0x7FDAFF0BB8A3
#8  0x7FDAFF0D09AC
#9  0x7FDAFF0D0BA4
#10  0x7FDAFF0D0AC4
#11  0x7FDAFF0D0CEB
#12  0x7FDAFF0D09E4
#13  0x7FDAFF0D0CEB
#14  0x7FDAFF0D09E4
#15  0x7FDAFF0C1477
#16  0x7FDAFF0CFCAF
#17  0x7FDAFF323A1A
#18  0x7FDAFF317070
#19  0x7FDAFF31A68C
#20  0x7FDAFF31C44A
#21  0x7FDAFF31ECA7
#22  0x7FDAFF31615B
#23  0x43FA31 in adios_flexpath_close
#24  0x40BDB1 in common_adios_close
#25  0x407CC5 in adios_close_
#26  0x405620 in writearray_ at genarray_stream.F90:228
#27  0x406D99 in MAIN__ at genarray_stream.F90:110
```
This is the output I see for staged_write:
```
Input stream            = staged.out                                            
Output stream           = regular.out                                           
Read method             = FLEXPATH (id=5)                                       
Read method parameters  = "max_chunk_size=100; app_id =32767;                   
verbose= 3;poll_interval  =  100;"                                              
Write method            = MPI                                                   
Write method parameters = ""                                                    
                                                                                
Waiting to open stream staged.out...                                            
DETECTED FAILED EVENT WRITE                                                     
Warning!  Write failed for output action 1 on stone 1, event likely not transmitted                                                                             
   -  Bridge stone local stone number 1 disabled
```

**Comment by sujin-philip** [comment]
The crash does not occur on the latest master and the example seems to work correctly.
