### ISSUE TITLE
Python: adios.File inheritance gives errors upon __del__

### ISSUE THREAD

**Issue by jimgreen** [ornladios/ADIOS#188]
Naive empty inheritance 

```python
import gc

import adios
class myFile(adios.File):
    pass

for i in range(2):
    fname = "test.bp"
    gc.collect()
    fp = myFile(fname)
    fp.close()
```
gives errors like

```bash
Exception ignored in: <built-in method __del__ of myFile object at 0x2ad0c41f01a8>
Traceback (most recent call last):
  File "adios.pyx", line 1043, in adios.file.__del__ (adios.cpp:15561)
  File "adios.pyx", line 1055, in adios.file.close (adios.cpp:15817)
AssertionError: Not an open file
Exception ignored in: <built-in method __del__ of myFile object at 0x2ad0c41f00f8>
Traceback (most recent call last):
  File "adios.pyx", line 1043, in adios.file.__del__ (adios.cpp:15561)
  File "adios.pyx", line 1055, in adios.file.close (adios.cpp:15817)
AssertionError: Not an open file
```

No such problem for `h5py.File`. Any idea?

**Comment by jimgreen** [comment]
Thank you jy. I saw many diffs in cxx files. I'm using a Conda wheel version and it is not easy for me to verify for now. But your answer sounds right. Please close this issue if you feel it is solved. I will try to verify this later.
